- name: Get Existing ASA NTP Servers
  asa_command:
    commands:
      - "show run | i ntp server"
  register: current_ntp

- name: Configure ASA NTP Servers
  asa_config:
    src: templates/asa_ntp.j2
    save: yes
