- name: Get Existing ASA DNS Servers
  asa_command:
    commands: "sh run dns"
  register: current_dns

- name: Configure ASA DNS Servers
  asa_config:
    src: templates/asa_dns.j2
    replace: line
    save: yes
